### ISSUE TITLE
Itemdumper no longer working with memcached 1.5.1

### ISSUE THREAD

**Issue by fabriziobonavita** [quora/mcinspector#2]
Is there anyone still maintaining this project? And is there a chance to make it work with memcache 1.5.x+?

**Comment by fusiyuan2010** [comment]
Hi @fabriziobonavita , thanks for the report.

Actually it's possible to make it work on memcached after 1.5, and it has to be by having '-o inline_ascii_resp' option while starting the memcached server.

This is because the detection is based on a feature in the way mc storing the data internally.  However, 1.5.x made 'modern' mode as default which enabled 'no_inline_ascii_resp' thus invalidated this detection hack. 

Maybe there can be other detection method which needs not this workaround, but I can't promise that.
